# Generated by Django 4.0.6 on 2022-08-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.CharField(default='', max_length=10, unique=True)),
                ('Vertical', models.BooleanField(default=False)),
                ('InitHorizontalCoord', models.IntegerField(default=0)),
                ('InitVerticalCoord', models.IntegerField(default=0)),
                ('Clue', models.CharField(default='', max_length=200, unique=True)),
            ],
        ),
    ]
