# Generated by Django 4.0.6 on 2022-08-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossword', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='Answer',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='Clue',
            new_name='clue',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='InitHorizontalCoord',
            new_name='initialHorizontal',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='InitVerticalCoord',
            new_name='initialVertical',
        ),
        migrations.RenameField(
            model_name='word',
            old_name='Vertical',
            new_name='vertical',
        ),
        migrations.AddField(
            model_name='word',
            name='complete',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='word',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
